apiVersion: v1
kind: ConfigMap
metadata:
  name: drawio-config
data:
  drawio-config.json: |
    {
      "templateFile": "/templates/templates.xml",
      "realtimeUrl": "https://drawio-dev.fairkom.net/cache",
      "pusherKey": "local-rt"
    }
