apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - issuer.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - drawio-configmap.yaml
  - realtime-server-deployment.yaml
  - realtime-server-service.yaml

images:
  - name: jgraph/drawio
    newTag: "30.0.2"

labels:
  - pairs:
      app: drawio
      environment: base